require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/galeris", type: :request do
  include Rails.application.routes.url_helpers
  # This should return the minimal set of attributes required to create a valid
  # Galeri. As you add validations to Galeri, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # then in an example


  describe "GET /index" do
    it "renders a successful response" do
      sign_in FactoryBot.create(:account)
      Galeri.create! valid_attributes
      get galeris_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      galeri = Galeri.create! valid_attributes
      get galeri_url(galeri)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      sign_in FactoryBot.create(:account)
      get new_galeri_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      galeri = Galeri.create! valid_attributes
      get edit_galeri_url(galeri)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Galeri" do
        expect {
          post galeris_url, params: { galeri: valid_attributes }
        }.to change(Galeri, :count).by(1)
      end

      it "redirects to the created galeri" do
        post galeris_url, params: { galeri: valid_attributes }
        expect(response).to redirect_to(galeri_url(Galeri.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Galeri" do
        expect {
          post galeris_url, params: { galeri: invalid_attributes }
        }.to change(Galeri, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post galeris_url, params: { galeri: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested galeri" do
        galeri = Galeri.create! valid_attributes
        patch galeri_url(galeri), params: { galeri: new_attributes }
        galeri.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the galeri" do
        galeri = Galeri.create! valid_attributes
        patch galeri_url(galeri), params: { galeri: new_attributes }
        galeri.reload
        expect(response).to redirect_to(galeri_url(galeri))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        galeri = Galeri.create! valid_attributes
        patch galeri_url(galeri), params: { galeri: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested galeri" do
      galeri = Galeri.create! valid_attributes
      expect {
        delete galeri_url(galeri)
      }.to change(Galeri, :count).by(-1)
    end

    it "redirects to the galeris list" do
      galeri = Galeri.create! valid_attributes
      delete galeri_url(galeri)
      expect(response).to redirect_to(galeris_url)
    end
  end
end
